config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
   resources :pages do
     get :page_parts, :on => :collection
     get :clear, :on => :collection
     member do
       post 'preview'
     end
   end
   resources :snippets
 		resources :menus do
 			resources :menu_items
 		end
 		resources :contacts
 	end

  namespace :cms do
    resource :sitemap, :only => "show"
  end

  root :to => 'pages#show'

end

app/controllers/admin/snippets_controller.rb
class Admin::SnippetsController < Admin::ApplicationController
  belongs_to_spud_app :snippets
  add_breadcrumb "Snippets", :admin_snippets_url

  before_filter :load_snippet, :only => [:show, :edit, :update, :destroy]

  def index
    @snippets = SpudSnippet.site(session[:admin_site]).order(:name).paginate :page => params[:page]
    respond_with @snippets
  end

  def new
    add_breadcrumb "New", :new_admin_snippet_url
    @snippet = SpudSnippet.new
    respond_with @snippet
  end

  def create
    add_breadcrumb "New", :new_admin_snippet_url
    @snippet = SpudSnippet.new(snippet_params)
    @snippet.site_id = session[:admin_site]

    @snippet.save

    respond_with @snippet, :location => admin_snippets_url
  end

  def edit
    add_breadcrumb "Edit", :edit_admin_snippet_url

    respond_with @snippet
  end

  def update
    add_breadcrumb "Edit", :edit_admin_snippet_url
    flash[:notice] = "Snippet saved successfully!" if @snippet.update_attributes(snippet_params)
    respond_with @snippet, :location => admin_snippets_url
  end

  def destroy
    flash[:notice] = "Snippet removed!" if @snippet.destroy
    respond_with @snippet,:location => admin_snippets_url
  end


private
  def load_snippet
    @snippet = SpudSnippet.where(:id => params[:id]).first
    if @snippet.blank?
      flash[:error] = "Snippet does not exist!"
      redirect_to admin_snippets_url and return false
    elsif Spud::Core.multisite_mode_enabled && @snippet.site_id != session[:admin_site]
      flash[:warning] = "This snippet is for a different site"
      redirect_to admin_snippets_url and return false
    end
  end

  def snippet_params
    params.require(:spud_snippet).permit(:content, :content_processed, :format, :name)
  end

end

app/views/admin/snippets/_form.html.erb
<fieldset>
  <%= f.label :name, :required=>true,:style =>"display:none;" %>
  <%= f.text_field :name, :class => "full-width",:placeholder=>"Enter title here" %>
</fieldset>
<br/>
<div>
  <%= f.text_area :content,:style => "width:100%;", :class => 'tinymce full-width' %>
</div>

app/views/admin/snippets/edit.html.erb
<%=form_for @snippet,:url => admin_snippet_path(@snippet),:html=>{:class=>"form-horizontal"} do |f|%>
  <%=render :partial => "form",:locals => {:f => f}%>
  <div class="form-actions">
    <%=f.submit "Save Snippet", :class=>"btn btn-primary"%> or <%=link_to "cancel",admin_snippets_path,:class => "btn"%>
  </div>

<%end%>

app/views/admin/snippets/index.html.erb
<%=content_for :data_controls do%>
<%=link_to "New Snippet",new_admin_snippet_path(),:class => "btn btn-primary",:title => "New Snippet"%>
<%end%>
<%=content_for :detail do%>
  <div class="page_list">
      <%@snippets.each do |snippet|%>
        <div class="page_row">

          <span class="row_meta"><%=link_to snippet.name,edit_admin_snippet_path(:id => snippet.id)%></span>

          <span class="edit_controls">

            <%=link_to "Remove",admin_snippet_path(:id => snippet.id),:method => :delete,:class => 'btn btn-danger', :data => {:confirm => "Are you sure you want to remove this snippet?"} %>
          </span>
          <br style="clear:both;"/>
        </div>
      <%end%>
      <%=will_paginate @snippets%>

  </div>



<%end%>

app/views/admin/snippets/new.html.erb
<%=form_for @snippet,:url => admin_snippets_path,:html=>{:class=>"form-horizontal"} do |f|%>
  <%=render :partial => "form",:locals => {:f => f}%>
  <div class="form-actions">
    <%=f.submit "Create Snippet", :class=>"btn btn-primary"%> or <%=link_to "cancel",admin_snippets_path,:class => "btn"%>
  </div>

<%end%>