config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
   resources :pages do
     get :page_parts, :on => :collection
     get :clear, :on => :collection
     member do
       post 'preview'
     end
   end
   resources :snippets
 		resources :menus do
 			resources :menu_items
 		end
 		resources :contacts
 	end

  namespace :cms do
    resource :sitemap, :only => "show"
  end

  root :to => 'pages#show'

end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < Admin::ApplicationController
	belongs_to_spud_app :menus
	add_breadcrumb "Menus", :admin_menus_path
	before_filter :load_menu,:only => [:edit,:update,:show,:destroy]

	def index
		@menus = SpudMenu.site(session[:admin_site]).order(:name).paginate :page => params[:page]
		respond_with @menus
	end


	def new
		add_breadcrumb "New", :new_admin_menu_path
		@menu = SpudMenu.new
		respond_with @menu
	end

	def create
		add_breadcrumb "New", :new_admin_menu_path
		@menu = SpudMenu.new(menu_params)
		@menu.site_id = session[:admin_site]
		flash[:notice] = "New menu created" if @menu.save
		respond_with @menu,:location => @menu.id != nil ? admin_menu_menu_items_url(:menu_id => @menu.id) : admin_menus_url
	end

	def edit
		add_breadcrumb "Edit #{@menu.name}", :edit_admin_menu_path
		respond_with @menu
	end

	def update
		add_breadcrumb "Edit #{@menu.name}", :edit_admin_menu_path

		flash[:notice] = "Menu saved successfully" if @menu.update_attributes(menu_params)
		respond_with @menu,:location => admin_menu_menu_items_url(:menu_id => @menu.id)
	end

	def destroy
		flash[:notice] = "Menu removed!" if @menu.destroy
		respond_with @menu,:location => admin_menus_url
	end

private

	def load_menu
		@menu = SpudMenu.where(:id => params[:id]).first
		if @menu.blank?
			flash[:error] = "Menu not found!"
			redirect_to admin_menus_url() and return false
		elsif Spud::Core.multisite_mode_enabled && @menu.site_id != session[:admin_site]
			flash[:warning] = "Site Context Changed. The menu you were viewing is not associated with the current site. Redirected back to menu selections."
			redirect_to admin_menus_url() and return false
		end
	end

	def menu_params
		params.require(:spud_menu).permit(:name)
	end

end

app/views/admin/menus/_form.html.erb
<%=error_messages_for(f.object)%>
<fieldset>
<div class="control-group">
	<%=f.label :name, :required=>true,:class => "control-label"%>
	<div class="controls">
	  <%=f.text_field :name,:title => "",:size=>40%>
	</div>

</div>
</fieldset>

app/views/admin/menus/edit.html.erb
  

  <%=form_for @menu,:url => admin_menu_path(:id => @menu.id),:html=>{:class=>"form-horizontal"} do |f|%>
    <%=render :partial => "form",:locals => {:f => f}%>
    <div class="form-actions">
    	<%=f.submit "Save Menu", :class=>"btn btn-primary"%> or <%=link_to "cancel",admin_menus_path,:class => "btn"%>
    </div>

  <%end%>

app/views/admin/menus/index.html.erb
<% content_for :data_controls do%>
	<%= link_to "New Menu",new_admin_menu_path(),:class => "btn btn-primary",:title => "New Menu" %>
<% end %>
<%=content_for :detail do%>
	<div class="page_list">
			<%@menus.each do |menu|%>
				<div class="page_row">
					
					<span class="row_meta"><%=link_to menu.name,admin_menu_menu_items_path(:menu_id => menu.id)%></span>

					<span class="edit_controls">
						<%=link_to "Edit",edit_admin_menu_path(:id => menu.id),:class => 'btn'%>
						<%=link_to 'Items', admin_menu_menu_items_path(:menu_id => menu.id), :class => 'btn' %>
						<%=link_to "Remove",admin_menu_path(:id => menu.id),:method => :delete,:class => 'btn btn-danger', :data => {:confirm => "Are you sure you want to remove this menu and all items associated with it?"}%>
					</span>
					<br style="clear:both;"/>
				</div>
			<%end%>
			<%=will_paginate @menus%>
	</div>	
<%end%>

app/views/admin/menus/new.html.erb
<%=form_for @menu,:url => admin_menus_path,:html=>{:class=>"form-horizontal"} do |f|%>
  <%=render :partial => "form",:locals => {:f => f}%>
  <div class="form-actions">
    <%=f.submit "Create Menu", :class=>"btn btn-primary"%> or <%=link_to "cancel",admin_menus_path,:class => "btn"%>
  </div>

<%end%>